### ISSUE TITLE
$ f \colon X \to Y \semicolon x \mapsto y $ に相当するnewcommandの追加の検討

### ISSUE THREAD

**Issue by CptHaus** [ykyki/extop-tex#77]
\morphを使うのであれば$ f \colon X \to Y \semicolon x \mapsto y $に対応するコマンドも追加したほうがいいのではないでしょうか.

**Comment by ykyki** [comment]
`\morph` 追加時に少し考えましたが、使用頻度が多くなりそうかどうかの予測がつかなかったため保留し、必要になったら再検討しようと思っていました。

必要そうであれば、追加してもらって構いません。命名や `list-commands-table.tex` への登録はお任せします。
